version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
      - "5000:5000"
    volumes:
      - ./backend/db.json:/app/backend/db.json
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 